# Generated by Django 5.1.4 on 2025-06-03 01:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('empresas', '0001_initial'),
        ('mantenedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EveAntecedentesEventos',
            fields=[
                ('id_antecedente', models.AutoField(primary_key=True, serialize=False)),
                ('antecedente', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'eve_antecedentes_eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveAtributosEventos',
            fields=[
                ('id_atributo', models.IntegerField(primary_key=True, serialize=False)),
                ('id_evento', models.IntegerField()),
                ('valor_numerico', models.FloatField(blank=True, null=True)),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eve_atributos_eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveAtributosSubtipos',
            fields=[
                ('id_atributo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_valor', models.CharField(max_length=20)),
                ('obligatorio', models.CharField(max_length=2)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'eve_atributos_subtipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveDocumentosEventos',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_archivo', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'eve_documentos_eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveEstados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'eve_estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveEstadosEventos',
            fields=[
                ('id_nr', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'eve_estados_eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveImagenesEventos',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('archivo', models.ImageField(upload_to='eventos/imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eve_imagenes_eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveProcedencias',
            fields=[
                ('id_procedencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'eve_procedencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveSubtipos',
            fields=[
                ('id_subtipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('prioridad', models.CharField(max_length=20)),
                ('alerta_encendida', models.CharField(max_length=2)),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'eve_subtipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveTipos',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'eve_tipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveValoresListas',
            fields=[
                ('id_valor_lista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'eve_valores_listas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveEventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('direccion', models.CharField(max_length=500)),
                ('latitud', models.CharField(max_length=30)),
                ('longitud', models.CharField(max_length=30)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('alerta_encendida', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=2)),
                ('fecha_alerta', models.DateTimeField(blank=True, null=True)),
                ('observaciones_cierre', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('procesado_ia', models.CharField(blank=True, max_length=2, null=True)),
                ('procesado_ia_fecha', models.DateTimeField(blank=True, null=True)),
                ('id_comuna', models.ForeignKey(blank=True, db_column='id_comuna', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mantenedores.admcomunas')),
                ('id_dispositivo', models.ForeignKey(blank=True, db_column='id_dispositivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dispositivos.disdispositivos')),
                ('id_estado_actual', models.ForeignKey(blank=True, db_column='id_estado_actual', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.eveestados')),
                ('id_procedencia', models.ForeignKey(db_column='id_procedencia', on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.eveprocedencias')),
                ('id_sensor', models.ForeignKey(blank=True, db_column='id_sensor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dispositivos.dissensores')),
                ('id_subtipo', models.ForeignKey(db_column='id_subtipo', on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.evesubtipos')),
                ('id_sucursal', models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresas.empsucursales')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.evetipos')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eve_eventos',
                'managed': True,
            },
        ),
    ]
