# Generated by Django 5.1.4 on 2025-06-03 01:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpEmpresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_representante', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_representante', models.CharField(blank=True, max_length=20, null=True)),
                ('email_representante', models.CharField(blank=True, max_length=60, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.CharField(max_length=2)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'emp_empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpRedApoyo',
            fields=[
                ('id_nr', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'emp_red_apoyo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpSucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=120)),
                ('latitud', models.CharField(max_length=30)),
                ('longitud', models.CharField(max_length=30)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'emp_sucursales',
                'managed': False,
            },
        ),
    ]
