# Generated by Django 5.1.4 on 2025-06-03 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmPerfiles',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'adm_perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id_archivo', models.AutoField(db_column='ID_ARCHIVO', primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(db_column='NOMBRE_ARCHIVO', max_length=60)),
                ('nombre_muestra', models.TextField(db_column='NOMBRE_MUESTRA')),
                ('ruta', models.CharField(blank=True, db_column='RUTA', max_length=30, null=True)),
            ],
            options={
                'db_table': 'archivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveIaMail',
            fields=[
                ('id_ia_mail', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.IntegerField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'eve_ia_mail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveIaResumen',
            fields=[
                ('id_ia_resumen', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.IntegerField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eve_ia_resumen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveIaTelefono',
            fields=[
                ('id_ia_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'eve_ia_telefono',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveMatchPersonas',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('id_evento', models.IntegerField()),
                ('alerta_encendida', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'eve_match_personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveMatchVehiculos',
            fields=[
                ('id_vehiculo', models.IntegerField(primary_key=True, serialize=False)),
                ('id_evento', models.IntegerField()),
                ('alerta_encendida', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'eve_match_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvePersonasEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.IntegerField()),
                ('id_evento', models.IntegerField()),
                ('id_tipo_persona', models.IntegerField()),
            ],
            options={
                'db_table': 'eve_personas_eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EveVehiculosEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vehiculo', models.IntegerField()),
                ('id_evento', models.IntegerField()),
            ],
            options={
                'db_table': 'eve_vehiculos_eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(db_column='ID_MENU', primary_key=True, serialize=False)),
                ('nombre_menu', models.CharField(blank=True, db_column='NOMBRE_MENU', max_length=60, null=True)),
                ('id_menu_padre', models.IntegerField(blank=True, db_column='ID_MENU_PADRE', null=True)),
                ('codigo_menu', models.CharField(blank=True, db_column='CODIGO_MENU', max_length=4, null=True)),
                ('activo', models.CharField(blank=True, db_column='ACTIVO', max_length=2, null=True)),
                ('id_archivo', models.IntegerField(blank=True, db_column='ID_ARCHIVO', null=True)),
                ('icono', models.CharField(blank=True, db_column='ICONO', max_length=30, null=True)),
                ('tiene_hijo', models.CharField(blank=True, db_column='TIENE_HIJO', max_length=2, null=True)),
                ('nivel', models.CharField(blank=True, db_column='NIVEL', max_length=10, null=True)),
                ('link_especial', models.CharField(blank=True, db_column='LINK_ESPECIAL', max_length=60, null=True)),
                ('orden', models.IntegerField(blank=True, db_column='ORDEN', null=True)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulos', models.AutoField(db_column='ID_MODULOS', primary_key=True, serialize=False)),
                ('nombre_modulos', models.CharField(db_column='NOMBRE_MODULOS', max_length=30)),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModulosArchivos',
            fields=[
                ('id_archivo', models.OneToOneField(db_column='ID_ARCHIVO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='utilidades.archivos')),
            ],
            options={
                'db_table': 'modulos_archivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModulosMenu',
            fields=[
                ('id_modulos', models.OneToOneField(db_column='ID_MODULOS', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='utilidades.modulos')),
            ],
            options={
                'db_table': 'modulos_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvePersonasEventosPK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.IntegerField()),
                ('id_evento', models.IntegerField()),
                ('id_tipo_persona', models.IntegerField()),
            ],
            options={
                'db_table': 'eve_personas_eventos',
                'managed': True,
                'unique_together': {('id_persona', 'id_evento')},
            },
        ),
    ]
