# Generated by Django 5.1.4 on 2025-06-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmComunas',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'adm_comunas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdmEstadosCiviles',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'adm_estados_civiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdmGenero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'adm_genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdmPaises',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('iso', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'adm_paises',
                'managed': False,
            },
        ),
    ]
