# Generated by Django 5.1.4 on 2025-06-03 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehMarcasVehiculos',
            fields=[
                ('id_marca_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'veh_marcas_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehTiposVehiculos',
            fields=[
                ('id_tipo_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'veh_tipos_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehVehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=60, null=True)),
                ('color', models.CharField(blank=True, max_length=60, null=True)),
                ('lista_gris', models.CharField(max_length=2)),
                ('activo', models.CharField(max_length=2)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'veh_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehVehiculosGrises',
            fields=[
                ('id_nr', models.AutoField(primary_key=True, serialize=False)),
                ('id_vehiculo', models.IntegerField()),
                ('accion', models.CharField(max_length=10)),
                ('id_usuario', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'veh_vehiculos_grises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_camino', 'En Camino')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='asignado', max_length=20)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.eveeventos')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.cuadrilla')),
            ],
        ),
    ]
