# Generated by Django 5.1.4 on 2025-06-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisCompaniasSim',
            fields=[
                ('id_compania_sim', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'dis_companias_sim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisDispositivos',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('endpoint1', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint2', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('latitud', models.CharField(max_length=30)),
                ('longitud', models.CharField(max_length=30)),
                ('habilitado', models.CharField(max_length=2)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'dis_dispositivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisSensores',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_unico', models.CharField(max_length=20, unique=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('habilitado', models.CharField(max_length=2)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'dis_sensores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisTiposDispositivos',
            fields=[
                ('id_tipo_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'dis_tipos_dispositivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisTiposSensores',
            fields=[
                ('id_tipo_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'dis_tipos_sensores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisTiposSim',
            fields=[
                ('id_tipo_sim', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'dis_tipos_sim',
                'managed': False,
            },
        ),
    ]
