# Generated by Django 5.1.4 on 2025-06-03 01:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EveTiposPersonas',
            fields=[
                ('id_tipo_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'eve_tipos_personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilArchivosActivos',
            fields=[
                ('id_tipo_perfil', models.IntegerField(db_column='ID_TIPO_PERFIL', primary_key=True, serialize=False)),
                ('id_menu', models.IntegerField(db_column='ID_MENU')),
            ],
            options={
                'db_table': 'perfil_archivos_activos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPerfiles',
            fields=[
                ('id_tipo_perfil', models.AutoField(db_column='ID_TIPO_PERFIL', primary_key=True, serialize=False)),
                ('nombre_perfil', models.CharField(db_column='NOMBRE_PERFIL', max_length=60)),
                ('id_direccion', models.IntegerField(db_column='ID_DIRECCION')),
                ('activo', models.CharField(db_column='ACTIVO', max_length=2)),
            ],
            options={
                'db_table': 'tipo_perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPersonas',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('paterno', models.CharField(max_length=60)),
                ('materno', models.CharField(blank=True, max_length=60, null=True)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('lista_gris', models.CharField(max_length=2)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'per_personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPersonasGrises',
            fields=[
                ('id_nr', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=10)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'per_personas_grises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerUsuariosPerfiles',
            fields=[
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100)),
                ('id_perfil', models.IntegerField()),
            ],
            options={
                'db_table': 'per_usuarios_perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPerfilesMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo_perfil', models.IntegerField(blank=True, db_column='ID_TIPO_PERFIL', null=True)),
                ('id_menu', models.IntegerField(blank=True, db_column='ID_MENU', null=True)),
                ('activo', models.CharField(blank=True, db_column='ACTIVO', max_length=2, null=True)),
            ],
            options={
                'db_table': 'tipo_perfiles_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_persona', models.IntegerField(db_column='ID_PERSONA', primary_key=True, serialize=False)),
                ('clave', models.CharField(db_collation='latin1_swedish_ci', db_column='CLAVE', max_length=120)),
                ('activo', models.CharField(blank=True, db_column='ACTIVO', max_length=2, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilModulos',
            fields=[
                ('id_tipo_perfil', models.OneToOneField(db_column='ID_TIPO_PERFIL', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='personas.tipoperfiles')),
            ],
            options={
                'db_table': 'perfil_modulos',
                'managed': False,
            },
        ),
    ]
